package utils

import (
	"bytes"
	"image/png"
	"sync"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestGenerateQRCodePNG(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		data string
	}{
		{name: "empty", data: ""},
		{name: "url", data: "https://example.com/vmess://abc123"},
		{name: "special characters", data: "https://example.com/path?query=value&foo=bar#anchor"},
		{name: "unicode", data: "https://example.com/привет/世界"},
		{name: "vless url", data: "vless://abc123-uuid@example.com:443?encryption=none&security=reality&type=tcp&headerType=none#My%20Server"},
		{name: "long data", data: "https://example.com/path?data=" + repeatString("a", 500)},
		{name: "binary-like data", data: string([]byte{0x00, 0x01, 0x02, 0x03, 0xff, 0xfe, 0xfd})},
		{name: "newlines", data: "line1\nline2\nline3"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			pngData, err := GenerateQRCodePNG(tt.data)
			require.NoError(t, err)
			require.GreaterOrEqual(t, len(pngData), 8)
			require.Equal(t, []byte{0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a}, pngData[:8])
			_, err = png.Decode(bytes.NewReader(pngData))
			require.NoError(t, err, "generated bytes must be a decodable PNG")
		})
	}
}

func TestGenerateQRCodePNG_DeterministicAndDistinct(t *testing.T) {
	t.Parallel()

	first, err := GenerateQRCodePNG("https://example.com/consistent")
	require.NoError(t, err)
	second, err := GenerateQRCodePNG("https://example.com/consistent")
	require.NoError(t, err)
	require.Equal(t, first, second, "same input should produce deterministic output")

	other, err := GenerateQRCodePNG("https://example.com/different")
	require.NoError(t, err)
	require.NotEqual(t, first, other, "different inputs should produce different output")
}

func TestGenerateQRCodePNG_Concurrent(t *testing.T) {
	t.Parallel()

	const (
		workers   = 8
		perWorker = 8
		input     = "https://example.com/concurrent"
	)

	results := make(chan []byte, workers*perWorker)
	errs := make(chan error, workers*perWorker)
	var wg sync.WaitGroup
	wg.Add(workers)

	for i := 0; i < workers; i++ {
		go func() {
			defer wg.Done()
			for j := 0; j < perWorker; j++ {
				pngData, err := GenerateQRCodePNG(input)
				if err != nil {
					errs <- err
					continue
				}
				results <- pngData
			}
		}()
	}

	wg.Wait()
	close(results)
	close(errs)

	for err := range errs {
		require.NoError(t, err)
	}

	var first []byte
	count := 0
	for pngData := range results {
		if first == nil {
			first = pngData
		} else {
			require.Equal(t, first, pngData, "concurrent generation must be deterministic")
		}
		count++
	}
	require.Equal(t, workers*perWorker, count)
}

func BenchmarkGenerateQRCodePNG(b *testing.B) {
	data := "https://example.com/vless://abc123-uuid@example.com:443?encryption=none&security=reality"
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		if _, err := GenerateQRCodePNG(data); err != nil {
			b.Fatal(err)
		}
	}
}

func BenchmarkGenerateQRCodePNG_Parallel(b *testing.B) {
	data := "https://example.com/test"
	b.RunParallel(func(pb *testing.PB) {
		for pb.Next() {
			if _, err := GenerateQRCodePNG(data); err != nil {
				b.Fatal(err)
			}
		}
	})
}

func repeatString(s string, n int) string {
	result := make([]byte, 0, len(s)*n)
	for i := 0; i < n; i++ {
		result = append(result, s...)
	}
	return string(result)
}
